ARG IMAGE_NAME
ARG IMAGE_VERSION
FROM ${IMAGE_NAME}:${IMAGE_VERSION}
RUN mkdir -p /app
WORKDIR /app
COPY pom.xml pom.xml
RUN mvn clean install
# COPY . .
ENTRYPOINT ["/bin/bash", "echo jjj"]
# RUN mvn test
CMD ["./runner.sh"]
